language: php
os: linux
dist: noble

jobs:
  include:
    - php: 8.2
      env: VERSIONS=--prefer-lowest
    - php: 8.3
    - php: 8.4
      env: COLLECT_COVERAGE=true

install:
  - travis_retry composer self-update --2
  - travis_retry composer install --no-interaction
  - travis_retry composer update $VERSIONS

script:
  - vendor/bin/phpunit

after_success:
  - if [[ "$COLLECT_COVERAGE" == "true" ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover build/logs/coverage.xml; fi
